# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Sentipix
                                 A QGIS plugin
 downloading Sentinel-2 and Sentinel-3 data and performing image processing tasks
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-06-25
        copyright            : (C) 2023 by anas chammam
        email                : anas.chammam@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Sentipix class from file Sentipix.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Sentipix import Sentipix
    return Sentipix(iface)
